### ISSUE TITLE
Resolving of ::class constant is not working

### ISSUE THREAD

**Issue by fprochazka** [pbyrne84/DynamicReturnTypePlugin#66] opened 2017-02-26 15:25 UTC
Hi,
I'm pretty sure this worked in the past, but now it doesn't. In the following screenshots, I've focused the `getId` method and opened documentation for it.

![image](https://cloud.githubusercontent.com/assets/158625/23340953/86f4649c-fc3f-11e6-9a30-d794476a1ae3.png)

![image](https://cloud.githubusercontent.com/assets/158625/23340957/916f4f4a-fc3f-11e6-87b2-aafc3c8b57de.png)

The full configuration is [here](https://github.com/fprochazka/posobota-2017-02-model-workshop/blob/740b2868143d3cc9ac188add48082fd2870f77b7/docs/phpstorm/dynamicReturnTypeMeta.json#L195-L214), relevant part looks like this

```json
{
  "methodCalls": [
    {
      "class": "\\Doctrine\\ORM\\EntityManager",
      "method": "find",
      "position": 0
    }
  ]
}
```

---

I'm currently running on the latest eap

![image](https://cloud.githubusercontent.com/assets/158625/23340993/23c736a0-fc40-11e6-8f1a-eb7a9bda5858.png)

![image](https://cloud.githubusercontent.com/assets/158625/23341006/58394540-fc40-11e6-8482-36278a7a50ce.png)

**Comment by markussom** [comment] 2017-02-26 22:04
Duplicate of #65

**Comment by fprochazka** [comment] 2017-02-26 23:08
Sorry :-/

**Closed** 2017-02-26 23:09 UTC
